#!/bin/sh

RUBY_VERSION=ruby-2.0.0-p247
MD5_HASH=c351450a0bed670e0f5ca07da3458a5b
CFLAGS="-march=k8 -O2 -pipe"

mkr_fetch()
{
	if [ ! -f "$RUBY_VERSION".tar.gz ]; then
		ftp http://cache.ruby-lang.org/pub/ruby/"$RUBY_VERSION".tar.gz
	fi

	if [ "$MD5_HASH" != `md5 -q "$RUBY_VERSION".tar.gz` ]; then
		echo "MD5 checksum does not match!\nDelete $RUBY_VERSION.tar.gz and rerun mkruby fetch"
	fi
}

mkr_extract()
{
	if [ ! -d "$RUBY_VERSION" ]; then
		if [ -f "$RUBY_VERSION".tar.gz ]; then
			tar -xzvf "$RUBY_VERSION".tar.gz
		fi
	fi
}

mkr_build()
{
	if [ -d "$RUBY_VERSION" ]; then
		cd $RUBY_VERSION
		export CFLAGS="$CFLAGS"
		patch -p0 < ../patches/patch-common_mk
		patch -p0 < ../patches/patch-lib_fileutils_rb
		patch -p0 < ../patches/patch-lib_rubygems_dependency_installer_rb
		patch -p0 < ../patches/patch-lib_rubygems_ext_builder_rb
		./configure --with-opt-dir=/usr/local
		make
		unset CFLAGS
		cd ..
	fi
}

mkr_install()
{
	if [ -d "$RUBY_VERSION" ]; then
		cd $RUBY_VERSION
		sudo make install
		cd ..
	fi
}

case "$1" in
	'all')
		mkr_fetch
		mkr_extract
		mkr_build
		mkr_install
		;;
	'fetch')
		mkr_fetch
		;;
	'extract')
		mkr_extract
		;;
	'build')
		mkr_build
		;;
	'install')
		mkr_install
		;;
	*)
		echo "usage: mkruby [all|fetch|extract|build|install]"
esac
