#!/bin/sh

RUBY_VERSION=ruby-1.9.3-p392
MD5_HASH=f689a7b61379f83cbbed3c7077d83859
CFLAGS="-march=k8 -O2 -pipe"

mkr_fetch()
{
	if [ ! -f "$RUBY_VERSION".tar.gz ]; then
		ftp ftp://ftp.ruby-lang.org/pub/ruby/"$RUBY_VERSION".tar.gz
	fi

	if [ "$MD5_HASH" !=  `md5 -q "$RUBY_VERSION".tar.gz` ]; then
		echo "MD5 checksum does not match!\nDelete $RUBY_VERSION.tar.gz and rerun mkruby fetch"
	fi
}

mkr_extract()
{
	if [ ! -d "$RUBY_VERSION" ]; then
		if [ -f "$RUBY_VERSION".tar.gz ]; then
			`tar -xzvf "$RUBY_VERSION".tar.gz`
		fi
	fi
}

mkr_build()
{
	if [ -d "$RUBY_VERSION" ]; then
		cd $RUBY_VERSION
		./configure --with-opt-dir=/usr/local
		CFLAGS="$CFLAGS" make -e
		cd ..
	fi
}

mkr_install()
{
	if [ -d "$RUBY_VERSION" ]; then
		cd $RUBY_VERSION
		sudo make install
		cd ..
	fi
}

case "$1" in
	'fetch')
		mkr_fetch
		;;
	'extract')
		mkr_extract
		;;
	'build')
		mkr_build
		;;
	'install')
		mkr_install
		;;
	*)
		echo "usage: mkruby [fetch|extract|build|install]"
esac